version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/live/app
    networks:
      - app-network
    entrypoint: npm install
networks:
  app-network:
    driver: bridge